"""Added_Driver

Revision ID: 0a2d6cbf8eb8
Revises: 318f95a7a7dc
Create Date: 2024-04-22 09:59:17.451737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2d6cbf8eb8'
down_revision = '318f95a7a7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('car_model', sa.String(length=64), nullable=False),
    sa.Column('license_plate', sa.String(length=64), nullable=False),
    sa.Column('password_hashed', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_car_model'), ['car_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_driver_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_license_plate'), ['license_plate'], unique=True)
        batch_op.create_index(batch_op.f('ix_driver_middle_name'), ['middle_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_middle_name'))
        batch_op.drop_index(batch_op.f('ix_driver_license_plate'))
        batch_op.drop_index(batch_op.f('ix_driver_last_name'))
        batch_op.drop_index(batch_op.f('ix_driver_first_name'))
        batch_op.drop_index(batch_op.f('ix_driver_email'))
        batch_op.drop_index(batch_op.f('ix_driver_car_model'))

    op.drop_table('driver')
    # ### end Alembic commands ###
