"""Added order_finished column

Revision ID: 13c26a1b67fe
Revises: d47374a6e1d8
Create Date: 2024-05-20 20:41:16.394093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c26a1b67fe'
down_revision = 'd47374a6e1d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('number_of_ratings',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_finished', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_order_finished'), ['order_finished'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_order_finished'))
        batch_op.drop_column('order_finished')

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('number_of_ratings',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
