"""Removed car model

Revision ID: 318f95a7a7dc
Revises: b3de3d906f4b
Create Date: 2024-04-18 12:57:26.957834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318f95a7a7dc'
down_revision = 'b3de3d906f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_car_model')
        batch_op.drop_column('car_model')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_model', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_user_car_model', ['car_model'], unique=False)

    # ### end Alembic commands ###
