"""empty message

Revision ID: 35998805e3fe
Revises: 937c91ca63e9
Create Date: 2024-05-08 13:57:11.377034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35998805e3fe'
down_revision = '937c91ca63e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_taked', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_order_taked'), ['order_taked'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_order_taked'))
        batch_op.drop_column('order_taked')

    # ### end Alembic commands ###
