"""orders table

Revision ID: 87ffdbb7e16e
Revises: 59876ae651c5
Create Date: 2024-04-07 13:09:14.192673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ffdbb7e16e'
down_revision = '59876ae651c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_start', sa.String(length=140), nullable=False),
    sa.Column('place_end', sa.String(length=140), nullable=False),
    sa.Column('price', sa.String(length=140), nullable=False),
    sa.Column('order_time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_order_time'), ['order_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_order_time'))

    op.drop_table('order')
    # ### end Alembic commands ###
