"""Roles

Revision ID: 937c91ca63e9
Revises: 93e0a0ebf2b1
Create Date: 2024-04-24 20:28:14.647939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937c91ca63e9'
down_revision = '93e0a0ebf2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
