"""Taxi Driver

Revision ID: 93e0a0ebf2b1
Revises: 0a2d6cbf8eb8
Create Date: 2024-04-22 11:15:51.594055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e0a0ebf2b1'
down_revision = '0a2d6cbf8eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_driver_id', 'driver', ['driver_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_driver_id', type_='foreignkey')
        batch_op.drop_column('driver_id')

    # ### end Alembic commands ###
