"""User

Revision ID: 9c67d231a60f
Revises: 18575ed4f7b9
Create Date: 2024-04-15 15:18:14.387638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c67d231a60f'
down_revision = '18575ed4f7b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_model', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_car_model'), ['car_model'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_car_model'))
        batch_op.drop_column('car_model')

    # ### end Alembic commands ###
