"""added hashed

Revision ID: 9d80da75285e
Revises: 35998805e3fe
Create Date: 2024-05-11 18:24:29.539003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d80da75285e'
down_revision = '35998805e3fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name_hashed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_name_hashed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('middle_name_hashed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('email_hashed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('car_model_hashed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('license_plate_hashed', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name_hashed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('last_name_hashed', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('email_hashed', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_hashed')
        batch_op.drop_column('last_name_hashed')
        batch_op.drop_column('first_name_hashed')

    with op.batch_alter_table('driver', schema=None) as batch_op:
        batch_op.drop_column('license_plate_hashed')
        batch_op.drop_column('car_model_hashed')
        batch_op.drop_column('email_hashed')
        batch_op.drop_column('middle_name_hashed')
        batch_op.drop_column('last_name_hashed')
        batch_op.drop_column('first_name_hashed')

    # ### end Alembic commands ###
