"""orders table

Revision ID: b9efc79cd89b
Revises: 87ffdbb7e16e
Create Date: 2024-04-07 21:32:25.938749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9efc79cd89b'
down_revision = '87ffdbb7e16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
