"""Time of travel

Revision ID: cdfc56f9bd85
Revises: 62ccd10f9231
Create Date: 2024-05-22 17:06:54.933157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfc56f9bd85'
down_revision = '62ccd10f9231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_of_travel', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('time_of_travel')

    # ### end Alembic commands ###
